### ISSUE TITLE
Bug bei Vorlagen

### ISSUE THREAD

**Issue by vulpesaquae** [InvisibleUSA/METLAB_News#100]
Ablauf:
Vorlage erstellen  -> scheint erfolgreich
Vorlage abrufen -> scheint an sich erfolgreich, es wird aber keine Vorlage von der Query zurückgegeben

Aufruf über das Administrator Dashboard, Debugging bis in Methoden des ProfileManager: createNewProfileTemplate, getAvailableTemplates

QueryAddProfileTemplate enthält nach Aufruf bei template die korrekten Informationen der Vorlage und bei result ""
QueryGetProfileTemplatesByOrganisation enthält nach Aufruf keine Ergebnisse

**Comment by ede1998** [comment]
Fehler lag nicht nur in der Query, die reingegebenen Daten waren auch falsch:
```xml
<organisation>me.metlabnews.Model.Entities.Organisation@47981ec8</organisation>
```

fixed in 03fc939
