### ISSUE TITLE
Login / Logout / Login Exception

### ISSUE THREAD

**Issue by Toberto91** [InvisibleUSA/METLAB_News#102]
Wenn ich mich einlogge, auf Ausloggen drücke und mich wieder einloggen möchte erscheint folgende Exception:

![image](https://user-images.githubusercontent.com/37065718/40625133-e0947e0a-62b0-11e8-8472-353bc75c6a7d.png)

**Comment by vulpesaquae** [comment]
addressed in commit 9d6e4bc
