### ISSUE TITLE
YaCy / Clipping Generator Error

### ISSUE THREAD

**Issue by Toberto91** [InvisibleUSA/METLAB_News#104]
nur zur Vollständigkeit. Ist wahrscheinlich der gleiche Fehler wie bei https://github.com/InvisibleUSA/METLAB_News/issues/103

![image](https://user-images.githubusercontent.com/37065718/40625503-340b2d5c-62b3-11e8-89ba-c0b4547fee36.png)

**Comment by ede1998** [comment]
Liegt daran weil bei dir lokal kein yacy läuft, und er sich daher nicht damit verbinden kann

**Comment by Toberto91** [comment]
Wie installiere ich lokal yacy? Gibt es dafür eine Anleitung (bzw. unsere Logindaten) ?
