### ISSUE TITLE
Profil löschen nicht mehr möglich

### ISSUE THREAD

**Issue by Toberto91** [InvisibleUSA/METLAB_News#105]
Funktioniert sporadisch (nicht). Ich bekomme meins nicht mehr gelöscht. Wo werden denn die ObservationsProfile gespeichert?

**Comment by ede1998** [comment]
Lokal in BaseXData

**Comment by ede1998** [comment]
Wieso kannst du es nicht mehr löschen? Ohne mehr Infos braucht man da nicht schauen...

**Comment by Toberto91** [comment]
Nachdem ich mir einige Profile erstellt, wieder gelöscht und wieder erstellt habe, lies sich mein zuletzt erstelltes Profil nicht mehr löschen und ich habe dauerhaft E-Mails erhalten.

**Comment by Toberto91** [comment]
fixed
