### ISSUE TITLE
Feedback nach 'Profil erstellen'

### ISSUE THREAD

**Issue by Toberto91** [InvisibleUSA/METLAB_News#107]
Bitte ein kleines Feedback nach 'Profil erstellen' hinzufügen. Aktuell passiert nichts im Frontend

**Comment by vulpesaquae** [comment]
Da ist Feedback im Code, genau das gleich wie bei Vorlage erstellen. Nur wird es bei der Vorlage sofort ausgeführt (Felder werden geleert plus Meldung) und bei Profil erst, wen eine weitere Interaktion mit Vaadin Componenten auftritt, zB Quellen aktualisieren. Kein Plan woran das liegen könnte, ich hab die entsprechenden Codefragmente in SubscriberDashboardView, MainUI und ProfileManager nebeneinander verglichen und kein Unterschied festgestellt.

**Comment by MarcoRempfer** [comment]
Ja, ist ein Vaadin Fuckup.

**Comment by Toberto91** [comment]
not fixed, but nevermind.... not working. fuck off
