### ISSUE TITLE
Bilder für Produktwebsite erstellen

### ISSUE THREAD

**Issue by InvisibleUSA** [InvisibleUSA/METLAB_News#11]

**Comment by Toberto91** [comment]
Produktwebseite erstellt, Bilder hinzugefügt

**Comment by ede1998** [comment]
> Produktwebseite erstellt, Bilder hinzugefügt
Wie meinst du das? Hast du tatsächlich eine Produktwebsite erstellt?
Ich dachte du wolltest eine Projektwebsite machen.

Außerdem: Bitte einen Verweis darauf, wenn so was verkündest. So lässt es sich schnell finden.

**Comment by Toberto91** [comment]
> Wie meinst du das? Hast du tatsächlich eine Produktwebsite erstellt?
Ich dachte du wolltest eine Projektwebsite machen.

> Außerdem: Bitte einen Verweis darauf, wenn so was verkündest. So lässt es sich schnell finden

War ein Versehen. Meinst du mit der Produktwebseite dann die Webapplikation? Die würde ich sagen machen wir auf Lukas' Webspace. Dort mit HTML und CSS.

Was genau meinst du mit Bilder erstellen? Logo's?

**Comment by InvisibleUSA** [comment]
Begriffserklaerung:
Produktwebsite - Die Website wo die Webapplikation drauf laeuft
Projektwebsite - Die Website wo unsere Dokumentation veroeffentlicht wird

**Comment by Toberto91** [comment]
Ok.

Projektwebsite: https://metlabnews.wixsite.com/metlab-news
Produktwebsite: Link von Projektwebsite -> "Webapplikation"

**Comment by MarcoRempfer** [comment]
Kann man dieses Issue schließen?

**Comment by Toberto91** [comment]
closed, weil keiner checkt was hier gemeint ist.
