### ISSUE TITLE
Crawler Shutdown Methode

### ISSUE THREAD

**Issue by Toberto91** [InvisibleUSA/METLAB_News#113]
@BentiGorlich hat eine Schnittstelle dafür bereitgestellt, bitte ein UI-Mensch (Marco, Achim) das implementieren !!

**Comment by vulpesaquae** [comment]
Was genau für Methoden gibts in der Richtung? Also Shutdown, Start und Abruf des aktuellen Status?
Soll denn im Systemadministrator-Interface ne Anzeige des aktuellen Zustands und n Knopf als Trigger hin?

**Comment by Toberto91** [comment]
@BentiGorlich

**Comment by BentiGorlich** [comment]
du muss einfach im CrawlerController die Methode Stop aufrufen. Der beendet dann von sich aus alle Crawler die gerade laufen...
Wirkliche Statusmethoden habe ich nicht implementiert

**Comment by vulpesaquae** [comment]
ist im Systemadmin Dashboard, die Knöpfe rufen nur die Start/Stopmethoden auf.
Kann der Start/Stop fehlschlagen? Wenn ja wäre dafür noch ne Rückmeldung praktisch.
schau mal ob es deinen Vorstellungen entspricht

**Comment by BentiGorlich** [comment]
funktioniert
