### ISSUE TITLE
QueryGetSubscribersOfOrganisation gibt nicht alle Subscriber zurück

### ISSUE THREAD

**Issue by vulpesaquae** [InvisibleUSA/METLAB_News#114]
QueryGetSubscribersOfOrganisation gibt nur den ersten Subscriber zurück
Die verwendete Organisation ist Beispielfirma, die neun Nutzer hat.

Aufruf über getSubscribersOfOrganisation im Model/BusinessLogic/UserManager

![image](https://user-images.githubusercontent.com/37065828/40877940-44f9cb8a-6689-11e8-8920-d33430807134.png)

**Comment by InvisibleUSA** [comment]
Ist gefixt
