### ISSUE TITLE
Clipping Darstellung in UI

### ISSUE THREAD

**Issue by vulpesaquae** [InvisibleUSA/METLAB_News#115]
wirft aktuell Exceptions

**Comment by MarcoRempfer** [comment]
Welche Exceptions werden wann geworfen?

**Comment by vulpesaquae** [comment]
inzwischen andere, ich arbeite dran

**Comment by vulpesaquae** [comment]
Jetzt wird exakt die Mail des Clippings in der UI angezeigt.
Sollte dafür noch eine Variante ohne mailspezifische Elemente aus dem Clipping generiert werden? Also ohne so unsubscribe newsletter und so, des braucht man in der online Ansicht ja nich

**Comment by MarcoRempfer** [comment]
Lass gut sein
