### ISSUE TITLE
Darstellungsfehler des Kalenders auf README.md

### ISSUE THREAD

**Issue by MarcoRempfer** [InvisibleUSA/METLAB_News#17]
Siehe OneNote:

https://onedrive.live.com/view.aspx?resid=8657C4A14FEECE8D%211495&id=documents&wd=target%28Bugs.one%7C431FE40C-1460-4333-B44D-51E234F25824%2FKalender%20auf%20GitHub-Pages%7CD8F31D9B-4810-4315-8C1C-D0E5E9D9C75E%2F%29
onenote:https://d.docs.live.net/8657c4a14feece8d/Documents/METLAB_News/Bugs.one#Kalender%20auf%20GitHub-Pages&section-id={431FE40C-1460-4333-B44D-51E234F25824}&page-id={D8F31D9B-4810-4315-8C1C-D0E5E9D9C75E}&object-id={1BF2CD19-2360-4854-BB4A-E986DC9FF361}&12

**Comment by MarcoRempfer** [comment]
Ist natürlich nicht wichtig, könnte sich aber vielleicht trotzdem mal jemand drum kümmern.
Ich wollte euch vorallem mal exemplarisch zeigen, wie ich mir Bug-Reports vorstelle:
1) Neues Issue mit Kurzbeschreibung und 'bug'-Label
2) Neue OneNote Page in der entsprechenden Kategorie mit genauer Beschreibung, ggf. Screenshots, Log
    Files, etc.
3) Bei GitHub auf die OneNote Page verlinken
4) Auf der OneNote Page die Issue Number vermerken

Warum nicht einfach alles bei GitHub dokumentieren?
Weil es unübersichtlich wird. Bei OneNote können die Infos besser kategorisiert werden, was uns viel Zeit und Ärger sparen kann.
Wenn jemand ein besseres Tools kennt, können wir gern drüber reden, aber ich habe beruflich sehr gute Erfahrungen mit OneNote gemacht.

**Comment by ede1998** [comment]
was bietet onenote fuer vorteile gegenueber github? Ínwieweit lassen sich infos besser kategorisieren?

Zum Bug: es ist bekannt, dass manchmal der Kalender angezeigt wird und manchmal nicht

**Comment by MarcoRempfer** [comment]
Man kategorisiert über Abschnitte, Seiten und Unterseiten
Man kann bequem das ganze Notizbuch nach bestimmeten Begriffen durchsuchen
Man kann schneller von einee Seite zu einer anderen wechseln
Man hat Zeichentools und bessere Formatierungsmöglichkeiten

**Comment by InvisibleUSA** [comment]
Das sollte man morgen mal besprechen

**Comment by MarcoRempfer** [comment]
@InvisibleUSA @ede1998 würdet ihr dieses Issue bitte nicht ständig reopen?
Wir sollten die OneNote Diskussion unter dem Issue mit dem Titel "OneNote" führen, nicht hier.
Dieses Issue hier ist ein Bug-Report, der sich erledigt hat.
