### ISSUE TITLE
Recherchebericht zu Ende bringen

### ISSUE THREAD

**Issue by ede1998** [InvisibleUSA/METLAB_News#21]
- [x] Genauere Betrachtung eines Produkts @BentiGorlich 
- [x] Bericht erstellen @MarcoRempfer

**Comment by BentiGorlich** [comment]
Betrachtung Echobot ist fertig

**Comment by ede1998** [comment]
Kannst du die Use Cases noch ausformulieren?

**Comment by BentiGorlich** [comment]
nicht selbsterklärend?

**Comment by ede1998** [comment]
habe es mir nochmal genauer angeschaut. Use Cases meint was anderes. Du hast Verwendungsszenarien gelistet. Use Case waere meiner Meinung nach eher Report erstellen

**Comment by BentiGorlich** [comment]
Was heißt Use-Cases denn wenn nicht genau das? ^^

**Comment by ede1998** [comment]
> Use Case waere meiner Meinung nach eher Report erstellen

Wie kann der Anwender die Software verwenden, was fuer Funktionen hat die Software und so weiter
- Report erstellen
- Account erstellen
- Archivierten Report abrufen
- ...

**Comment by BentiGorlich** [comment]
Naja dann habe ich das ja vorher schon gemacht. Is noch nicht 100% aber den großteil habe ich dann ja schon...

**Comment by BentiGorlich** [comment]
ups ^^
Naja den großteil davon habe ich dann ja... icherweitere das dann noch

**Comment by Toberto91** [comment]
Schaut mal bitte im OneDrive (shit-link vom Vorjahr) den Ordner "SWE-AVHdocs_public,rar", dort sind sämtliche Aufgabenblätter. Könnte man als Muster verwenden.
