### ISSUE TITLE
Aufwandserfassung nicht alle als Contributor

### ISSUE THREAD

**Issue by BentiGorlich** [InvisibleUSA/METLAB_News#23]
Absicht?
Wenn ja wie wollen wir das dann machen?

**Comment by ede1998** [comment]
Wie meinst du das?

**Comment by BentiGorlich** [comment]
Ich kann die Excel Datei nicht ändern weil ich kein Contributor bin

**Comment by ede1998** [comment]
Contributor sind alle Leute, die diese Datei bisher veraendert haben
