### ISSUE TITLE
OneNote irgendwo verlinken

### ISSUE THREAD

**Issue by BentiGorlich** [InvisibleUSA/METLAB_News#24]
OneNote für Notizen und Code-Dokumentation:
https://1drv.ms/u/s!Ao3O7k-hxFeGi1fWenQ_aAUnT3SS

**Comment by Toberto91** [comment]
OneNote ist auf der Projektwebseite unter dem Reiter "Organisation" verlinkt.
Webseite: https://metlabnews.wixsite.com/metlab-news
Passwort für Gästebereich: metlab12345
