### ISSUE TITLE
Github Pages entfernen

### ISSUE THREAD

**Issue by Toberto91** [InvisibleUSA/METLAB_News#25]
Neue PROJEKT-Webseite: https://metlabnews.wixsite.com/metlab-news
Passwort für Gästebereich: metlab12345

- Bitte auch die Readme.md (und alle dazugehörigen) Dateien entfernen, bzw. bearbeiten.
- Neue Homepage an Van Hoof senden (falls notwendig)

**Comment by ede1998** [comment]
README sollte nicht entfernt, sondern nur überarbeitet werden. Sie hat den Zweck, Dritte ueber das Repository und seinen Inhalt informieren.

**Comment by Toberto91** [comment]
- README überarbeitet
- Homepage Link erneuert
