### ISSUE TITLE
OneNote Link auf Projekthomepage

### ISSUE THREAD

**Issue by MarcoRempfer** [InvisibleUSA/METLAB_News#27]
Den Link auf OneNote bitte in den passwortgeschützten Bereich verschieben. Da soll nicht jeder reinschauen können.
Alternativ: OneNote auf der Homepage gar nicht verlinken, wäre mir noch viel lieber.

**Comment by Toberto91** [comment]
Sorry - dachte der komplette Unterbereich ist auch passwortgeschützt, wenn ich den Bereich "Organisation" mit einem Passwort versehe.

- Arbeitsrichtlinien entfernt
- OneNote entfernt
