### ISSUE TITLE
Projekthomepage Bilder Urheberrecht

### ISSUE THREAD

**Issue by MarcoRempfer** [InvisibleUSA/METLAB_News#28]
Sind diese Bilder urherberrechtlich abgesichert? Wir wären wirklich nicht die ersten, die für sowas verklagt werden.

**Comment by Toberto91** [comment]
Link zu den Bildern: https://www.pexels.com/search/newspaper/
Link zu den FAQ (Lizensen): https://www.pexels.com/faq/

Zitat 1:
What is the license of the photos on Pexels?
All photos on Pexels are licensed under the Creative Commons Zero (CC0) license. This means you can use them for free for any personal and commercial purpose. Attribution is not required. For more information read our license page.

Zitat 2:
Can I use the photos for a commercial project?
Yes, all photos are free for any commercial use. You can use them on your commercial website, print them on t-shirts or for any other legal purpose.

Zitat 3:
Do I need to mention the source or the photographer?
No, attribution is not required. But we are always happy if you mention Pexels ;)

**Comment by MarcoRempfer** [comment]
Ist erstmal gut, aber beim letzten Punkt kommt uns das deutsche Urheberrecht in die Quere. Demnach muss die Quelle genannt werden. Ein kleiner Hinweis im Impressum auf Pexels reicht wahrscheinlich aus.

**Comment by Toberto91** [comment]
Erledigt -> https://metlabnews.wixsite.com/metlab-news/impressum
