### ISSUE TITLE
Nutzerlogin + RDBMS

### ISSUE THREAD

**Issue by InvisibleUSA** [InvisibleUSA/METLAB_News#32]

**Comment by Toberto91** [comment]
Das Aufsetzten der MariaDB übernehme ich, um Lukas für die FSA Klausur zu entlasten.

**Comment by ede1998** [comment]
Im Designatudie gibt es schon fast ein Er modell, bitte dafür noch mit asta ein diagramm machen

**Comment by InvisibleUSA** [comment]
- [ ] Basic SQL Funktionen in eigene Klasse einfuegen @Toberto91

**Comment by Toberto91** [comment]
Befindet sich im SQL Branch. Für Mutations- und Abfragebefehle.
