### ISSUE TITLE
Brauche noch neue Queries

### ISSUE THREAD

**Issue by BentiGorlich** [InvisibleUSA/METLAB_News#48]
und zwar für: getSources(), addSource(Source source), titleExists(String title), addArticle(Article article)

**Comment by ede1998** [comment]
Marco hat die DB anschluss groesstenteils implementiert

**Comment by BentiGorlich** [comment]
ok dann merge ich das noch bei mir

**Comment by BentiGorlich** [comment]
auch aufm Database branch hats die Queries nicht...

**Comment by BentiGorlich** [comment]
in meinem Branch habe ich die jetzt implementiert
