### ISSUE TITLE
Arbeitskonventionen festlegen und dokumentieren

### ISSUE THREAD

**Issue by ede1998** [InvisibleUSA/METLAB_News#5]
Beispiele:
Codeformatting
Abspeichern von Textdokumenten in Richtext (rtf)
Abspeichern von Tabellen in csv

**Comment by Toberto91** [comment]
Fertig, siehe https://docs.wixstatic.com/ugd/e46385_3a7c1c8c706a4cb9811d1fa97ecae781.pdf
