### ISSUE TITLE
MariaDB: sporadisch auftretende Verbindungsprobleme

### ISSUE THREAD

**Issue by MarcoRempfer** [InvisibleUSA/METLAB_News#53]
Fehler beim Verbinden mit MariaDB auf dem Server:
"Host '46.101.223.95' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'"

Siehe OneNote.

**Comment by InvisibleUSA** [comment]
Ich glaube nicht das es mit 'mysqladmin flush-hosts' getan ist. Ich denke, dass im code irgendwas Verbindungsprobleme macht und dadurch auch nach dem flushen noch blocken würde.

**Comment by InvisibleUSA** [comment]
Das es später wieder funktioniert liegt wahrscheinlich daran, dass automatisch die hosts geflushed werden.

**Comment by MarcoRempfer** [comment]
Macht Sinn

**Comment by InvisibleUSA** [comment]
vielleicht mal auf dem Server selber mit localhost auf die DB zugreifen anstatt mit der ext. IP?

**Comment by MarcoRempfer** [comment]
Können wir in Zukunft machen, gibt dafür bereits ein Flag in Settings.xml

**Comment by MarcoRempfer** [comment]
Ok, Zugriff über localhost ist eingebaut und max_connect_errors steht jetzt auf 1000.
Warten wir einfach ab.
