### ISSUE TITLE
Missing spaces in console logging

### ISSUE THREAD

**Issue by InvisibleUSA** [InvisibleUSA/METLAB_News#54]
`#1288 | DEBUG | [11:32:15] : child PRICEat position 0requested. (Parent:CD)`

**Comment by Toberto91** [comment]
Meinst du das fehlende Leerzeichen bei "0requested" ? Oder was ist hiermit gemeint?

Für die Fehlermessage nach dem Timestamp ist jeder selbst verantwortlich.

**Comment by InvisibleUSA** [comment]
Ja und das „PRICEat“

Bitte mal derjenige der dafür verantwortlich ist fixen @everyone

**Comment by ede1998** [comment]
Das ist ne meldung von mir, ich fixe das noch,
ABER es waere so viel einfach, wenn du das selber gemacht haettest... Einen Rechtschreibfehler in der Ausgabe zu fixen sollte kein issue notwendig machen

**Comment by InvisibleUSA** [comment]
Ich hab aber keine Ahnung von welcher Klasse aus du das loggst. Vielleicht sollte man beim loggen noch den Namen der zugehörigen Klasse voranstellen.

**Comment by ede1998** [comment]
1) Du setzt einen Conditional Breakpoint in log, der triggered, wenn dieser String geloggt werden soll.
2) Du schaust in den StackTrace und schaust, wer gerade log aufgerufen hat.
3) du korrigierst den Fehler

ODER

1) du durchsuchst das ganze Projekt nach einem Substring davon, der sicher nicht dynamisch zusammengebaut wurde, zb "at position "
