### ISSUE TITLE
ConfigurationManager loggt falsch

### ISSUE THREAD

**Issue by BentiGorlich** [InvisibleUSA/METLAB_News#55]
wer auch immer die Enums im Logger umbenannt hat hat vergessen das im Configurationmanager auch zu machen

**Comment by ede1998** [comment]
schau doch ins git blame : D

**Comment by BentiGorlich** [comment]
ins was? ^^

**Comment by ede1998** [comment]
git blame
ist ein git befehl, mit dem du fuer jede zeile angezeigt bekommst, von wem sie ist,
geht auch ueber github oben rechts iwo auf der entsprechenden Datei Blame

**Comment by BentiGorlich** [comment]
ich würde das einfach beheben. Zumindest in meinem Branch

**Comment by MarcoRempfer** [comment]
Etwas detaillierter bitte.
Welche enums sind betroffen?

**Comment by BentiGorlich** [comment]
alle vom logger

**Comment by BentiGorlich** [comment]
Channel, LogPriority und LogType haben alle einen anderen Namen auf dem Dev Branch als auf jedem anderen

**Comment by MarcoRempfer** [comment]
Lösung: Refactor -> Rename

**Comment by Toberto91** [comment]
LogType existiert lange nicht mehr. Du solltest dir die aktuellste Version vom Logger mergen, da dort oft Änderungen vorgenommen werden. Ich arbeite nur auf dem dev-Branch.
