### ISSUE TITLE
Change the ERROR MESSAGE Notifications

### ISSUE THREAD

**Issue by InvisibleUSA** [InvisibleUSA/METLAB_News#58]
Following idea:

Change notifications like this:
`access(() -> Notification.show("Anmeldung fehlgeschlagen\n" + errorMessage, Notification.Type.ERROR_MESSAGE));`

![screen shot 2018-04-19 at 08 57 27](https://user-images.githubusercontent.com/26510839/38975858-b54cdc1c-43af-11e8-8999-dc2f7fa60008.png)

To notifications that look like this:
`Notification notif = new Notification("Anmeldung fehlgeschlagen\n" + errorMessage, Notification.Type.WARNING_MESSAGE);`
`notif.setDelayMsec(3000);` 
`access(() -> notif.show(Page.getCurrent()));`

![screen shot 2018-04-19 at 08 55 46](https://user-images.githubusercontent.com/26510839/38975794-79d3f062-43af-11e8-8155-7c7282da6a06.png)

**Comment by MarcoRempfer** [comment]
I approve.

**Comment by InvisibleUSA** [comment]
kleiner Tipp: es gibt reactions

**Comment by vulpesaquae** [comment]
Akzeptiert
