### ISSUE TITLE
Feedback after successfully adding Organization 

### ISSUE THREAD

**Issue by InvisibleUSA** [InvisibleUSA/METLAB_News#59]
Currently no feedback. Please add something like field clearing and/or a notification

**Comment by MarcoRempfer** [comment]
Man beachte: wir haben derzeit keine GUI.
Im dev Branch ist nur meine Mock-GUI.

**Comment by Toberto91** [comment]
Soweit ich gesehen habe ist ein Feedback vorhanden (falls die NullPointerException behoben wurde), falls nicht: re-open
