### ISSUE TITLE
Features bei der Benutzerverwaltung wiederherstellen

### ISSUE THREAD

**Issue by MarcoRempfer** [InvisibleUSA/METLAB_News#60]
Bei dem Merge vom Database-Branch mit dem dev-Branch sind eine Reihe von Dingen verloren gegangen:

- Unit Tests für Queries fehlen
- JavaDoc fehlt
- SQL-Anfragen werden in den Queries erstellt -> schlechtes Design
- **ist das ganze thread safe?**
- unnötige viele Queries (Login und GetVerificationStatus können z.B. zusammengelegt werden)
- Entities werden nicht benutzt?

Für mich ist nicht erkennbar, welche Vorteile dieser Merge hatte. Ist irgendetwas dadurch besser geworden?

**Comment by MarcoRempfer** [comment]
Und die Sprache in der Datanbank ist wohl Denglisch.

**Comment by MarcoRempfer** [comment]
Wie wäre es mit:
QueryAddUser qau = new QueryAddUser(adminFirstName, adminLastName, ...);

anstatt:
QueryAddUser qau = new QueryAddUser();
qau.firstName = adminFirstName;
qau.lastName = adminLastName;
...

**Comment by MarcoRempfer** [comment]
An mehreren Stellen im UserManager fehlt eine Fehlerbehandlung (nur teilweise mit TODOs markiert)
Die TODO: Implement waren schon mal erledigt...

**Comment by ede1998** [comment]
> Unit Tests für Queries fehlen

Inwieweit macht eine Unittesting der Queries ueberhaupt sinn?
der algorithmus, wie eine Query funktioniert ist immer der gleiche und nur die Anfragen unterscheiden sich. 
> SQL-Anfragen werden in den Queries erstellt -> schlechtes Design

Warum ist das schlechtes Design? Dadurch erfolgt eine Trennung von Zugriff auf die daten und dem Algorithmus, der die Daten braucht. 

> Entities werden nicht benutzt?

es kommt auf die Anfrage an, ob es sinnvoll ist entity objekt zu returnen

> ist das ganze thread safe?

BaseXConnector jetzt schon, dadurch sind automatisch auch alle Queries, die BaseX verwenden threadsafe

> Wie wäre es mit:
QueryAddUser qau = new QueryAddUser(adminFirstName, adminLastName, ...);

Ist eine Moeglichkeit, aber das soll dem Autor der jeweiligen Query offen gelassen werden. Das macht es problematisch, queries mehrmals zu verwenden, falls dies gewuenscht wird.

Der Rest ist glaube Aufgabe von @InvisibleUSA .

**Comment by MarcoRempfer** [comment]
UnitTests auf die Queries testen eine komplette Datenbankabfrage, also auch ob der Name der Tabelle bzw. der Spalte passt.

Wenn sich die SQL-Strings ändern (z.B. anderes DBMS als MariaDB), müssen alle Queries geändert werden. Deshalb schlechtes Design. Besser: die Queries im Connector erstellen.

Immer Entities zu benutzen schafft ein klares und konsistentes Interface.

Dann ist der MariDB Zugriff also nicht mehr thread-safe?

**Comment by ede1998** [comment]
@InvisibleUSA reminder

**Comment by InvisibleUSA** [comment]
@ede1998 WIP!!

**Comment by ede1998** [comment]
>Wenn sich die SQL-Strings ändern (z.B. anderes DBMS als MariaDB), müssen alle Queries geändert werden. Deshalb schlechtes Design. Besser: die Queries im Connector erstellen.

Muss auch sein, wenn die im Connector erstellt wuerden. Man kann ja in `MariaDBQueryBase` Konstanten fuer die Tabellennamen u.ä. erstellen, die die Unterqueries dann verwenden. So muss bei Aenderung eines Tabellennamens nur einmal was geaendert werden.

>anderes DBMS als MariaDB

Wird in diesem Projekt nicht passieren, also unnoetig sich darauf vorzubereiten
