### ISSUE TITLE
Null pointer exception in Configuration Manager

### ISSUE THREAD

**Issue by ede1998** [InvisibleUSA/METLAB_News#62]
Wenn dem CM eine Settings.xml gegeben wird, die nicht alle properties enthaelt, kann es zu einer Exception kommen:
einige Einstellungs Getter geben einen int oder double Wert zurueck. Dieser wird durch parseInt/Double aus ausgelesenen String gewonnen. Was passiert, wenn der eingelesene String null ist?
Weiterhin: was passiert wenn der ausgelesene String keine Zahl darstellt?

**Comment by Toberto91** [comment]
Die Leute müssen darauf achten, dass wenn sie die Methode eigenständig implementieren, dass diese auch ordnungsgemäß abgefangen werden. Dazu waren eigentlich ausreichend Beispiele im Quellcode vorhanden.
Ich habe jetzt mal alle Methoden angepasst. In Zukunft bitte darauf achten!
Boolean-parse wird automatisch auf false gesetzt, wenn dort etwas nicht stimmt oder der String leer ist.
