### ISSUE TITLE
Probleme mit Logger

### ISSUE THREAD

**Issue by ede1998** [InvisibleUSA/METLAB_News#68]
### Inkonsequente Bennenung der Channels
Die Channel fuer die Datenbanken heissen:
BaseX vs RDBMS

Das passt aber imo nicht ganz:
DODBMS (?) vs RDBMS
BaseX vs MariaDB
NoSQL vs SQL
waeren bezeichnungen die eher zueinander passen wuerden.

Kann man die die Channel umbenennen?

**Comment by BentiGorlich** [comment]
Bitte noch einen Info Channel dazu machen

**Comment by ede1998** [comment]
- Leerzeilen zwischen Logzeilen bitte entfernen
- Channels abschaltbar machen

**Comment by MarcoRempfer** [comment]
"DBMS" hab ich damals eingeführt, weil mein Connector völlig unabhängig vom konkreten System war. Der hätte auch mit PostgreSQL oder sonst was funktioniert (SQL Dialekt war in den Settings angegeben).
Der, der jetzt im dev Branch liegt, ist spezifisch für MariDB und könnte dann auch so heißen.
BaseX ist ebenfalls sehr spezifisch.

**Comment by MarcoRempfer** [comment]
@BentiGorlich wofür soll der gut sein?

**Comment by ede1998** [comment]
Loggen von Info Nachrichten, bsp Crawler wird gestartet, was in debug untergehen wurde

**Comment by Toberto91** [comment]
alles erledigt und im dev-branch

**Comment by ede1998** [comment]
bitte den commit mit angeben

**Comment by ede1998** [comment]
- Ich gehe davon aus, dass der info channel activity heisst?
- Wie filtere ich jetzt channels?

**Comment by Toberto91** [comment]
Dann habe ich das falsch verstanden. 

- INFO ist nun ein LogLevel
- Activity ist für sämtliche Aktivitäten im Programm (Klasse registriert sich, User registriert sich, User meldet sich an, Klasse hat sich initialisiert, etc....).
- Channels filterst du mit der Methode:
`Logger.getInstance().disableChannel(Logger.Channel.Default);`
Dies bitte im static initialiser im ResourceManager einbinden.

https://github.com/InvisibleUSA/METLAB_News/commit/69c83624671116c8723dc23a082b623c161359a1

**Comment by ede1998** [comment]
> Channels filterst du mit der Methode:
Logger.getInstance().disableChannel(Logger.Channel.Default);
Dies bitte im static initialiser im ResourceManager einbinden.

Ist doof als programm code, gehört in die Einstellung imo,

**Comment by ede1998** [comment]
> Channels filterst du mit der Methode:
Logger.getInstance().disableChannel(Logger.Channel.Default);
Dies bitte im static initialiser im ResourceManager einbinden.

funktioniert nicht, trage da mal sowas wie XMLTag ein, wenn du debug als level zulaesst

**Comment by Toberto91** [comment]
Muss nach der initialize Methode vom Logger aufgerufen werden, da in der initialize Methode erstmal alle zugelassen werden. Siehe letzter commit

**Comment by Toberto91** [comment]
Example:

```
package me.metlabnews.Model.Common;


import me.metlabnews.Model.DataAccess.ConfigurationManager;



public class Main
{


	public Main()
	{
		ConfigurationManager.getInstance().initialize();
		Logger.getInstance().initialize();
		Logger.getInstance().register(Main.class, Logger.Channel.Crawler);
		Logger.getInstance().disableChannel(Logger.Channel.Crawler);
		Logger.getInstance().logActivity(this, "test");

	}

	public static void main(String[] args)
	{
		Main m = new Main();
	}
}
```
