### ISSUE TITLE
Einigung darüber ob Strings oder Objekte zurückgegeben werden sollen

### ISSUE THREAD

**Issue by InvisibleUSA** [InvisibleUSA/METLAB_News#70]
Aktuell werden manchmal Objekte und manchmal Strings uebergeben.

Beispiele:
`public void getAllOrganisations(Session session, IGetStringArrayEvent onSuccess, IGenericFailureEvent onFailure)`  - hier werden Organisationen als String Array zurückgegeben.

`public void getPendingVerificationRequests(Session session, IUserInterface.IFetchPendingVerificationRequestsEvent onSuccess, IGenericFailureEvent onFailure)` - hier werden die Nutzer als UserDataRepresentation Array zurückgegeben.

**Comment by MarcoRempfer** [comment]
Objekte. Einfach, konsistent, eindeutig.

**Comment by InvisibleUSA** [comment]
Ganz meine Meinung. Dann bräuchte ich noch Events dafür in IUserinterface. Wer ist dafür zuständig?

**Comment by ede1998** [comment]
ich denke das hat sich?
