### ISSUE TITLE
Logger rekursiver Aufruf mit ConfigurationManager

### ISSUE THREAD

**Issue by ede1998** [InvisibleUSA/METLAB_News#73]
Fix that shit.

Please.

wenn log gar nicht erst configuration manager aufruft, kann das gar nicht passieren

**Comment by Toberto91** [comment]
Wenn ich den configmanager aus dem Logger entferne, dann sind alle Settings default. Wie oft denn noch?
Da du gerne deine Settings variabel einstellen möchtest, musst du den Logger (nach dem Configuration Manager) initialisieren.

Ohne initialisierung -> keine Settings -> alles default -> kein Error
Nicht alles korrekt initialisiert -> Exception / Error
Fehlende Settings.XML -> Error -> nachprüfen, ob bei System.getProperties("user.dir") der richtige Pfad steht.

Bitte genauere Beschreibung, was alles initialisiert wurde, wo der Fehler auftritt. Unter welchen Umständen er auftritt, und welcher Pfad die Settings.XML ausgibt. Ansonsten kann ich nichts fixen wenn es keine Fehlerbeschreibung mit den entsprechenden Umständen gibt.

**Comment by Toberto91** [comment]
Sollte nun ein für alle mal aus der Welt geschafft sein (hoffe ich).

https://github.com/InvisibleUSA/METLAB_News/commit/fade45adb3761248fb80a7abad2fb28300c5d207
