### ISSUE TITLE
Mails versenden

### ISSUE THREAD

**Issue by ede1998** [InvisibleUSA/METLAB_News#74]
Wie versende ich jetzt eine Mail?

Soweit ich das gesehen habe, hat die HTML klasse eine funktion.
``` Java
public boolean send(String to, String subject)
```

Wie versende ich damit eine sinnvolle Mail, wie gebe ich der Mail einen Inhalt?

**Comment by Toberto91** [comment]
Ich habe zu Test- und Debugzwecken den 3. Parameter "message" weggelassen und vergessen ihn wieder einzufügen.

Mails senden nun mit dieser Signatur:

`public boolean send(String to, String subject, String message);`

`String message = "Hallo Welt";
		
new HTMLMail()
{{
	send("test@test.de", "Subject", message);
        send("test@test.de", "Subject", getHTMLContent());  // Alternative über Object initializer direkt mit Zugriff auf HTMLcontent
}};`

Es ist dabei egal, ob die Message ein Plaintext ist oder HTML Content hat.

Ich würde sagen wir löschen die Simple-Mail Klasse und verwenden nur noch die HTML-Mail mit anderem Namen.

Die SimpleMail-Klasse wirft bei mir nach wie vor noch die Probleme, dass trotz richtigen Logindaten jedes mal der Fehler kommt, dass Username und Password falsch ist. Des Weiteren scheint es mit SSL bei mir Probleme zu geben, da du den Port 465 verwendet hast, der für SSL gedacht ist. Überall steht aber, dass der richtige funktionierende Port 587 sei. Leider hat dieser auch nicht bei mir funktioniert.

**Comment by Toberto91** [comment]
Das ist mir eigentlich relativ egal. Ich habe eine funktionierende Mail-Klasse bereitgestellt, die fähig ist HTML Mails zu versenden. Sehe keinen Diskussionsbedarf über den Sinn oder über den Nicht-Sinn. Wenn dir der Aufruf nicht passt, ergänze eine Overload Methode dazu.
