### ISSUE TITLE
Problem mit Pfad im ConfigurationManager und somit Fehler durch nicht vorhandene Settings.XML

### ISSUE THREAD

**Issue by Toberto91** [InvisibleUSA/METLAB_News#75]
Bitte mal durchtesten, und zwar bitte ALLE ! Es gibt ein Problem mit dem Pfad, dass bei mir der Zusatz .../Software/ nicht dabei steht und somit die Settings.XML aus dem ConfigurationManager niemals gefunden wird.

Irgendeine Klasse Main erstellen und folgenden Code einfügen:

```
public class Main
{
	public Main()
	{
		System.out.println(System.getProperty("user.dir"));
	}

	public static void main(String[] args)
	{
		Main m = new Main();
	}
}
```

Ergebnis? Bei mir:

> C:\Users\Tobi\IdeaProjects\METLAB_News

Wie es aussehen sollte:

> C:\Users\Tobi\IdeaProjects\METLAB_News\Software

Wie sieht das Ergebnis bei euch aus?

**Comment by InvisibleUSA** [comment]
Ergibnis auf Kali linux:

`/home/ln/IdeaProjects/METLAB_News`

**Comment by ede1998** [comment]
/home/erik/dhbw/swe/Metlab_News/Software

**Comment by InvisibleUSA** [comment]
@ede1998 welcher build? Welche JRE?

**Comment by Toberto91** [comment]
OK, dann haben wir das Problem erkannt. Jemand eine Idee wie man das fixen könnte?

**Comment by ede1998** [comment]
Wo ist das Problem?

**Comment by Toberto91** [comment]
? Hast du nicht oben 1 Ergebnis mit /Software und eines ohne gepostet

**Comment by InvisibleUSA** [comment]
Bei mir sind beide ohne

**Comment by InvisibleUSA** [comment]
Was ich nicht verstehe ist warum ich das /Sowftware/Software bekomme obwohl bei mir im Basepath kein Software ist

**Comment by InvisibleUSA** [comment]
Mein commit muesste es fixen

**Comment by ede1998** [comment]
Das ist aber ziemlich unsicher...
247ebacd8e2bc9b74b0f035d962e229363b747d4

Was ist, wenn jemand in seinem Path `Software` stehen hat?

**Comment by InvisibleUSA** [comment]
Dann machs besser.

**Comment by InvisibleUSA** [comment]
`System.getProperty("user.dir").endsWith("Software")`

So?

**Comment by ede1998** [comment]
Nein, das fliegt uns spaetestens auf dem Server um die Ohren..
`/opt/tomcat/Resources/Settings.XML` ist afaik der Pfad dort

**Comment by InvisibleUSA** [comment]
Dann funktioniert die vorherige loesung aber auch nicht.

**Comment by InvisibleUSA** [comment]
Ok aber es muss trotzdem Ueberall funktionieren

**Comment by ede1998** [comment]
`System.out.println(System.getProperty("user.dir"));` gibt das gleiche zurück wie pwd

**Comment by Toberto91** [comment]
Hat sich das eigentlich erledigt?

**Comment by InvisibleUSA** [comment]
Nicht wirklich. Muss noch auf dem Server probiert werden und ggf ne Lösung gefunden werden

**Comment by ede1998** [comment]
ich denke ich habe eine Loesung:
```java
public class T {
	public static void main(String... args)
	{
		System.out.println(T.class.getResource("T.class"));
	}
}
```

**Comment by Toberto91** [comment]
wurde das mittlerweile getestet und für funktionierend befunden?

**Comment by ede1998** [comment]
Nein ich habe nur einen lsg ansatz aufgezeigt

**Comment by ede1998** [comment]
Wer kuemmert sich jetzt darum?
Gibt es jmd, der grade nicht schon ne feste Aufgabe hat?

**Comment by Toberto91** [comment]
Am besten wäre wenn du es an jemanden delegierst; jemand der noch ein paar Stunden aufzuholen hat.

**Comment by ede1998** [comment]
Deswegen frage ich ja. 
@BentiGorlich hat afaik nicht so viel zu tun?
was ist mit @InvisibleUSA  und @Toberto91 ?

**Comment by ede1998** [comment]
ok macht eh niemand mehr
