### ISSUE TITLE
Loggen von (User-)Activities

### ISSUE THREAD

**Issue by Toberto91** [InvisibleUSA/METLAB_News#77]
Loggen von Benutzeraktivitäten in unserer Applikation. Beispiel:

- User registriert sich
- User meldet sich an
- SysAdmin meldet sich an
- User falsches Login
- etc.

Wo implementieren?

**Comment by MarcoRempfer** [comment]
In den Business Logic Klassen (UserManager, ProfileManager, etc.)

**Comment by Toberto91** [comment]
Implementiere ich in den nächsten Tagen
