### ISSUE TITLE
Mail error

### ISSUE THREAD

**Issue by InvisibleUSA** [InvisibleUSA/METLAB_News#78]
`09:12:11 ERROR: 535-5.7.8 Username and Password not accepted. Learn more at
09:12:11 535 5.7.8  https://support.google.com/mail/?p=BadCredentials k28-v6sm17425649wrk.46 - gsmtp`

**Comment by Toberto91** [comment]
Bitte HTMLMail nutzen. Simple Mail funktioniert zwar auch - jedoch gibt es hin und wieder Probleme mit der Google-Authentifizierung.

HTMLMail m = new HTMLMail();
m.send("test@test.de", "Subject", "Message goes here....");
