### ISSUE TITLE
Class Key not registered in Logger

### ISSUE THREAD

**Issue by Toberto91** [InvisibleUSA/METLAB_News#79]
![image](https://user-images.githubusercontent.com/37065718/39572746-b66bd798-4ed0-11e8-86c0-237fc1f2e523.png)

Die Registrierung muss INNERHALB der Klasse erfolgen. Ansonsten landet ein DEBUG aus KEY in UNREGISTERED_CHANNEL, da sich 'this' nur auf die Klasse bezieht und danach auch abgefragt wird.
Daraus folgt, dass DEBUG für KEY nicht ausschaltbar ist für den Logger. Folge: ca. 20.000 Zeilen DEBUG-Meldungen innerhalb von 1-2 Minuten.

Deshalb Key --> Registrierung innerhalb der Klasse.

**Comment by ede1998** [comment]
Hast du die Verwendung nochmals geändert? Der key hat schon mal in xml geloggt

**Comment by Toberto91** [comment]
![image](https://user-images.githubusercontent.com/37065718/39573193-7b57c23c-4ed2-11e8-89ec-1a792f8a276e.png)
Die HashTable sucht nach der VALUE, die mit 'this' als KEY übergeben wurde. Registriert wurde die VALUE aber mit 'Key.Class' Dadurch ist vermutlich der Hashwert anders und die Hashtabelle findet das Key-Value paar nicht, wenn man es mit 'this' aufruft.

**Comment by ede1998** [comment]
In der Pause?

**Comment by Toberto91** [comment]
sollte gefixed sein.
