### ISSUE TITLE
Logger Level deaktivieren geht nicht

### ISSUE THREAD

**Issue by BentiGorlich** [InvisibleUSA/METLAB_News#82]
wenn ich in der Settings Datei das LogLevel degug ausschalte funzt es nicht, also die Debug nachrichten werden immernoch geloggt...

Wenn ich aber von ToConsole zu ToFile ändere geht es nicht, also liegt es schonmal nicht an der Datei...

**Comment by Toberto91** [comment]
War ein kleineres Problem mit der logischen Verknüpfung des Logger. Sollte nun funktionieren.

https://github.com/InvisibleUSA/METLAB_News/commit/5e72c51df98868471213516e4f1f1376d472febf
