### ISSUE TITLE
XMLTag wirft NullPointerException bei 2. Processing Instruction

### ISSUE THREAD

**Issue by BentiGorlich** [InvisibleUSA/METLAB_News#84]
wenn man ein XML Dokument wie `<?xml version='1.0' encoding='UTF-8'?><?app?><channel></channel>` versucht zu parsen bekommt man eine NullPointerException

**Comment by ede1998** [comment]
du musst deinen xmlstring escapen, sonst sieht man ihn hier nicht
habe es jetzt korrigiert

**Comment by ede1998** [comment]
Also ich bekomme keine Nullpointer-Exception. XMLTag fragt das JavaXML-Zeug und das sagt, es ist invalides XML. Dementsprechend wird nie weiter konstruiert. Dann ist das zu erwartende Verhalten eine NullPointer-Exception (RTFM).
![grafik](https://user-images.githubusercontent.com/26464515/39676579-820263e2-516d-11e8-9fa5-06901d634deb.png)

**Comment by BentiGorlich** [comment]
oh ok.
Es ist aber kein invalides XML... und wenn ich es online in einen parser werfe bekomme ich auch keine Fehlermeldung...

**Comment by ede1998** [comment]
ich schaetze es ist invalid, aber der online parser vergibt mehr als der Java eigene
lass morgen ueberlegen, was zu tun ist

**Comment by BentiGorlich** [comment]
hmm ok...
das Problem ist halt dass die Suchergebnisse bei YaCy eben mit 2 PIs am Anfang kommen und man das nicht ausstellen kann...

**Comment by ede1998** [comment]
Vorschlag: XMLTag schmeisst alle PIs raus vor dem ubergeben an Javas XML

**Comment by BentiGorlich** [comment]
dann meckert er aber dass er ne version im xml tag bracuht,... wobei ich nicht weiß wie es ist wenn man gar kein xml tag am Anfang hat...

**Comment by ede1998** [comment]
Addressed in commit 3aaf0e9a9c6f10075c0a8f9779c8137141824d59
