### ISSUE TITLE
JavaDoc für abgeleitete Methoden

### ISSUE THREAD

**Issue by Toberto91** [InvisibleUSA/METLAB_News#85]
Wir brauchen eine **_einheitliche_** JavaDoc für abgeleitete Methoden.

Beispiel initialize(), close()

Des Weiteren sollten die getInstance()-Methoden auch einheitlich Dokumentiert sein.

**Comment by ede1998** [comment]
`@InheritDoc`?
Das geht für init und close

**Comment by Toberto91** [comment]
Wird das dann nur bei der Extrahierung der HTML / PDF - Datei mit vererbt oder gibt es auch eine Möglichkeit das direkt in der IResource zu dokumentieren und die Doku wird dann automatisch für alle ableitenden Klassen generiert? Hat nämlich gerade nicht funktioniert für die initialize().

Die close() wird ja von AutoCloseable abgeleitet, die ist gesperrt. Was gibt es hierfür für eine Lösung?

**Comment by ede1998** [comment]
> Wird das dann nur bei der Extrahierung der HTML / PDF - Datei mit vererbt oder gibt es auch eine Möglichkeit das direkt in der IResource zu dokumentieren und die Doku wird dann automatisch für alle ableitenden Klassen generiert? Hat nämlich gerade nicht funktioniert für die initialize().

Klar das geht nur in der extrahierten und geparsten Javadoc, so wioe link, @see und so weiter

> Die close() wird ja von AutoCloseable abgeleitet, die ist gesperrt. Was gibt es hierfür für eine Lösung?

Kann man in Java nicht die Funktion nochmal deklarieren und ne javadoc dazu machen?

**Comment by Toberto91** [comment]
> Kann man in Java nicht die Funktion nochmal deklarieren und ne javadoc dazu machen?

War auch meine erste Idee. Weiß ich leider nicht, ob das so funktioniert. @MarcoRempfer ? Weißt du das?

**Comment by MarcoRempfer** [comment]
Bietet das IntelliJ nicht an?

**Comment by Toberto91** [comment]
im Notfall füge ich mit copy & paste die Dinger manuell ein.
