### ISSUE TITLE
NullPointerException in SystemAdminDashboardView (beim Hinzufügen einer neuen Organisation)

### ISSUE THREAD

**Issue by Toberto91** [InvisibleUSA/METLAB_News#86]
![2018-05-08 10_13_11-whatsapp](https://user-images.githubusercontent.com/37065718/39745797-9f7caf40-52a8-11e8-9f23-7d1d037f651c.png)

Tritt bei jedem Hinzufügen von einer neuen Organisation auf. Sowohl im Dev-Branch als auch auf dem Webserver (vermutlich - da keine Notification).

Please fix asap. Eine nicht funktionsfähige Version zu releasen sollte eigentlich nicht sein.

**Comment by Toberto91** [comment]
@MarcoRempfer

**Comment by vulpesaquae** [comment]
Ich habs mir angeschaut und hab kein Plan, was an der Stelle die Exception verursacht oder in welcher Datei der Fehler ist. Meiner Einschätzung nach kann des in SystemAdminDashboardView, MainUI oder Presenter sein, aber ich weiß auch bei ner vergleichbaren, funktionerenden Funktion nicht, woher das onSuccess kommt
Also @MarcoRempfer

**Comment by MarcoRempfer** [comment]
@vulpesaquae da feht wahrscheinlich ein access in SystemAdminDashboardView

**Comment by vulpesaquae** [comment]
Ich weiß nicht wieso oder was das access geändert hat, aber es hat das Problem behoben ¯\\_(ツ)_/¯
