### ISSUE TITLE
Endspurt

### ISSUE THREAD

**Issue by Toberto91** [InvisibleUSA/METLAB_News#87]
Am Montag steht das finale Release und die Vorführung mit Van Hoof bevor. Bis dato sind die meisten anderen Gruppen schon fast fertig und haben wirklich optisch und funktional mega gute Anwendungen. Wir sollten deshalb gegen Ende nochmal ordentlich Gas geben, auch wenn es in der Lernphase ist, gibt es auch in SWE eine Note. Als Qualitäts- und Dokumentationsbeauftragter möchte ich deshalb, dass wir ein sauberes Projekt abliefern und kein Müll. Wir sollten uns die gut erarbeiteten Punkte für die erste Hälfte nicht durch Faulheit am Ende verspielen.

Hier sind nochmal die wichtigsten Dinge, die wir bis Sonntag noch erledigen müssen:
- [x] Architekturanpassung (nahezu alle von uns haben was abgeändert an ihren Klassen) im Designkonzept --> jeder sollte seine Klassendiagramme, Designbeschreibung etc. anpassen (die Datei hat Erik im Gdrive abgelegt!)
- [x] Finale Dokumentation als PDF/HTML (hierzu sind noch einige JavaDocs zu implementieren)
- [ ] Anleitung / Tutorial für unsere Anwendung
- [x] MainUI (allgemein Frontend) sollte definitiv noch ausgebaut werden in Thema Optik und Funktionalität (hier kann auch gerne jeder mithelfen @vulpesaquae @MarcoRempfer , wenn ihr Aufgaben delegieren wollt, dann tut es bitte)
- [x] Profil-/Nutzerverwaltung
- [ ] Präsentation (PPT) für Montag!!!
- [x] Unit-Tests (sind alle vorhanden oder fehlen noch welche?)
- [x] ...

Des Weiteren sollten wir ein ziemlich langes Meeting einplanen, in dem wir nochmals alle Sachen besprechen oder abarbeiten, an dem bitte JEDER teilnimmt. Ich bitte euch deshalb, mal kurz anzusagen, wann ihr denn KEINE Zeit habt, dann plane ich den/die Termin(e).

Falls noch irgendwas fehlt bei den o.g. Punkten, die noch zu erledigen sind dann bitte hier rein post, oder ein Issue erstellen. Spätestens Sonntag sollten dann alle Issues abgearbeitet sein.

**Comment by Toberto91** [comment]
Ich beginne gleich mal. Ich kann NICHT am Freitag und Samstag vor 15 Uhr.

**Comment by MarcoRempfer** [comment]
Könntest du dem Issue vielleicht noch ein paar Labels hinzufügen? Ich kann das sonst nicht einordnen.

**Comment by Toberto91** [comment]
@MarcoRempfer danke für den Hinweis ;-) wie sieht es bei dir aus zwecks Zeit für Meetings oder noch fehlenden TODOs ?

**Comment by MarcoRempfer** [comment]
Samstag von 15:00 bis 18:00 oder Sonntag würde gehen.

**Comment by ede1998** [comment]
Ich kann die ganze zeit. Will nur lernen, also bin flexibel von Termin her.


>Wir sollten deshalb gegen Ende nochmal ordentlich Gas geben, auch wenn es in der Lernphase ist, gibt es auch in SWE eine Note. 

Anmerkung: soweit ich weiß gibt es dafür so ziemlich die meisten ccts punkte

**Comment by Toberto91** [comment]
> Anmerkung: soweit ich weiß gibt es dafür so ziemlich die meisten ccts punkte

Es gibt 9 Credits dafür, zählt also sehr stark beim Schnitt mit

**Comment by vulpesaquae** [comment]
> Ich kann die ganze zeit. Will nur lernen, also bin flexibel von Termin her.

Geht mir auch so
