### ISSUE TITLE
BaseX input sanitization

### ISSUE THREAD

**Issue by ede1998** [InvisibleUSA/METLAB_News#88]
Pruefen wir eigentlich den BaseX-Input? Also verhindern wir Code-injection attacks gegen BaseX?

Das betrifft hauptsaechlich das Frontend, aber koennte auch den RSS Crawler betreffen.

**Comment by vulpesaquae** [comment]
Im UI jedenfalls nicht. Semantische Überprüfungen gehören denk ich in Model oder Controller. Und ich kenn mich mit BaseX nicht aus

**Comment by MarcoRempfer** [comment]
Sowas gehört logischerweise in in den BasXconnector.
Aber woher sollte denn überhaupt irgendwelcher BaseX Input kommen?

**Comment by ede1998** [comment]
Ist egal, wird sowieso nie produktiv eingesetzt...

Ausspäh-Angriffe wären  möglich über xQuery zb im keyword feld für Profile
