### ISSUE TITLE
Fails in Unit-Tests

### ISSUE THREAD

**Issue by Toberto91** [InvisibleUSA/METLAB_News#89]
![image](https://user-images.githubusercontent.com/37065718/39876163-c7c9a572-5472-11e8-93a3-b0425bfc37d6.png)

![image](https://user-images.githubusercontent.com/37065718/39876236-ed3a67f6-5472-11e8-9efe-187ecb0f14ae.png)

**Comment by ede1998** [comment]
addressed in commit 7c0c453c133f0322e9a9738fc5f189299d8a2ea3
