### ISSUE TITLE
Error in Unit Tests

### ISSUE THREAD

**Issue by Toberto91** [InvisibleUSA/METLAB_News#91]
[INFO] Total time: 4.456 s
[INFO] Finished at: 2018-05-13T11:30:52+02:00
[INFO] Final Memory: 29M/492M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project metlabnews: Compilation failure: Compilation failure:
[ERROR] /C:/Users/Tobi/IdeaProjects/METLAB_News/Software/Test/me/metlabnews/Model/Entities/ObservationProfileTest.java:[38,93] incompatible types: java.util.ArrayList<java.lang.String> cannot be converted to java.lang.String
[ERROR] /C:/Users/Tobi/IdeaProjects/METLAB_News/Software/Test/me/metlabnews/Model/ClippingDaemon/ClippingDaemonTest.java:[39,80] incompatible types: java.util.ArrayList<java.lang.String> cannot be converted to java.lang.String
[ERROR] /C:/Users/Tobi/IdeaProjects/METLAB_News/Software/Test/me/metlabnews/Model/ClippingDaemon/ClippingDaemonTest.java:[41,82] incompatible types: java.util.ArrayList<java.lang.String> cannot be converted to java.lang.String
[ERROR] /C:/Users/Tobi/IdeaProjects/METLAB_News/Software/Test/me/metlabnews/Model/DataAccess/DbConnectors/BaseXConnectorTest.java:[50,84] incompatible types: java.util.ArrayList<java.lang.String> cannot be converted to java.lang.String
[ERROR] -> [Help 1]

![image](https://user-images.githubusercontent.com/37065718/39965853-47718a3a-56a1-11e8-9b5c-d69490383215.png)

**Comment by ede1998** [comment]
@MarcoRempfer hat den Konstrukt or geändert, deswegen geht es jetzt nicht mehr

**Comment by Toberto91** [comment]
Ok, dann soll @MarcoRempfer erstmal alles fertig programmieren, die Tests sind nun erstmal zweitrangig.

**Comment by MarcoRempfer** [comment]
Wurde im Test geändert.
