### ISSUE TITLE
BUGFIXING: Fertigstellung des Projekts bis Dienstag, 05.06.2018 !

### ISSUE THREAD

**Issue by Toberto91** [InvisibleUSA/METLAB_News#92]
- [x] Bugfixing im Frontend
- [x] Bedienungsanleitung
- [x] Installationsanleitung
- [x] Dokumentation über Tests und Projekt
- [x] aktualisierte DVD

Bei Endabnahme:
- [x] Use Cases anhand von Checkliste abarbeiten und ihm präsentieren

**Comment by Toberto91** [comment]
[] Bedienungsanleitung
[] Installationsanleitung
[] Dokumentation über Tests und Projekt
[] aktualisierte DVD

**Comment by ede1998** [comment]
Noch ein Punkt, der verbessert werden sollte:
- [x] Unit-Test Coverage erhoehen


Wir haben bisher nur fuer einen (sehr) kleinen Teil unserer Software Unit-Tests. Das muss unbedingt mehr werden.
