### ISSUE TITLE
Bug in QueryGetProfileById

### ISSUE THREAD

**Issue by vulpesaquae** [InvisibleUSA/METLAB_News#93]
In ProfileManager.shareProfile(...) soll ein Profil an Hand der zuvor abgerufenen ID abgerufen werden. Die Query gibt schlägt nicht fehl, gibt aber null als Profil zurück. Siehe screenshot
![image](https://user-images.githubusercontent.com/37065828/40075618-0ae51e96-587d-11e8-8571-7f954f233537.png)

**Comment by ede1998** [comment]
Das if !execute ist falsch:
schau dir mal die javadoc dazu an: 
Das sagt nichts über den erfolg der speziellen query... 

wenn sie nicht erfolgreich ist würde ich null als profile erwarten

**Comment by ede1998** [comment]
Könnte aber durchaus sein, dass trotzdem ein fehler drin ist

**Comment by vulpesaquae** [comment]
Okay, das !execute ist richtig verwendet, aber dann fehlt noch ein Abfangen von "Profil nicht gefunden" @MarcoRempfer 
Die Query sollte trotzdem n Profil zurückgeben, zumindest hab ich die Profil ID mit der QueryGetProfilesByMail aus der Datenbank abgerufen

**Comment by ede1998** [comment]
Die fehler meldung ist falsch
Jedenfalls klingt sie falsch, weil das false auf dem execute sagt nichts aus drüber ob es das profil gibt

**Comment by vulpesaquae** [comment]
Naja, wenn die Datenbank nicht erreichbar ist, aber die Website schon, ist "unbekannter Fehler" denk ich schon angemessen. Für "Profil nicht gefunden" brauchts halt noch was separat davon, das auf m_profile == null reagiert

**Comment by ede1998** [comment]
Auf dem bild steht ne andere meldunf

**Comment by vulpesaquae** [comment]
Oh stimmt^^
Den Teil hab ich mir gar nich so genau angeschaut, weil der bei den abfragen immer sehr ähnlich aussieht. Dann muss des eventuell noch an mehr stellen angepasst werden

**Comment by ede1998** [comment]
addressed in commit 7dac1ad2a5b078e2de35b9c0376fd7264db9584c
