### ISSUE TITLE
Bug in QueryGetProfilesByEmail

### ISSUE THREAD

**Issue by vulpesaquae** [InvisibleUSA/METLAB_News#94]
QueryGetProfilesByEmail gibt zwar die korrekten Profile aus, allerdings nur die erste der Quellen. Das Profil wird laut Logger korrekt abgerufen, aber nicht korrekt weitergereicht (Screenshot)
(das selbe Problem könnte bei den Quellen auch der Fall sein)

```
<profile>
  <id>5000e21b-fd3a-47d7-a885-183956e8650c</id>
  <name>a,b,c</name>
  <owner>b</owner>
  <organisation>me.metlabnews.Model.Entities.Organisation@6b7e1dc2</organisation>
  <last-generation>2018-05-15T20:43:06</last-generation>
  <period>PT5M</period>
  <active>true</active>
  <keywords>
    <keyword>A,B,C</keyword>
  </keywords>
  <sources>
    <source>BBC News</source>
    <source>Gamestar</source>
    <source>SW Bote</source>
  </sources>
</profile>
```
![image](https://user-images.githubusercontent.com/37065828/40078838-200a7088-5886-11e8-9ffe-fe97f81bdebf.png)

**Comment by vulpesaquae** [comment]
Sieht bei den Suchbegriffen gleich aus wie bei den Quellen

**Comment by ede1998** [comment]
Ach so ich weiss woran das liegt

**Comment by ede1998** [comment]
Ok vllt auch nicht....
Ich schau morgen mal

**Comment by ede1998** [comment]
addressed in commit 7dac1ad2a5b078e2de35b9c0376fd7264db9584c
