### ISSUE TITLE
Artikel / Quellen crawlen

### ISSUE THREAD

**Issue by Toberto91** [InvisibleUSA/METLAB_News#96]
Ich weiß nicht genau, ob ich damit richtig liege. Aber wir haben am Tag der Abgabe sämtliche neue Quellen hinzugefügt: BILD, WELT, BBC, Focus, etc... Auf dem Screenshot in der Datenbank sind aber irgendwie nur 4 von 9 Artikelcounter > 0

Liegt das nur am RSS-Feed? Wird von Quellen, die kein RSS-Feed haben nichts gecrawled und somit auch kein Clipping versendet?

Es soll am Ende doch so sein, dass er uns eine Quelle nennt (Schwarzwälder Bote bspw.) und er dann darauf von dieser Quelle ein neues Clipping erhält.
EDIT: egal ob RSS oder nicht (eine andere Gruppe hat dafür mega den Einlauf kassiert, weil sie nur eins von beiden können)

Bitte mal um kurzes Feedback dazu.

![image](https://user-images.githubusercontent.com/37065718/40584288-bc03ec5a-619e-11e8-9a76-c86c8d066679.png)

**Comment by BentiGorlich** [comment]
Dieser Countertenor ist nie für Artikel die in der BaseX Datenbank sind, damit die eine GUID bekommen können. Das heißt der Countertenor ist nur für die RSS Crawler. Wenn etwas mir YaCy gecrawlt wird wird dieser Countertenor auch nicht hochgezählt

**Comment by Toberto91** [comment]
Könnte man vielleicht einen Counter nochmachen für YaCy ?

Damit man direkt auf den Ersten Blick sieht wieviele Artikel man von welcher Quelle und über welche Crawl-Art hat ?

**Comment by ede1998** [comment]
YaCy funktioniert anders
Du fragst YaCy nach einem RSS Feed fuer bestimmte KeyWords und dafuer bekommst du eine Antwort
Demnach ist der Counter fuer YaCy nicht aussagekraeftig

**Comment by BentiGorlich** [comment]
Erik liegt richtig. Und nein man kann keinen Countertenor für yacy machen. Dafür müsste man den Ort an dem der Index ist dauerhaft beobachten und analysieren... Dafür haben wir keine Zeit, keine Lust und es hat keinen Sinn... Und da wir keinen Zugriff auf die Funktionsweise von YaCy haben können wir da auch nichts machen

**Comment by BentiGorlich** [comment]
Der Counter wird bei YaCy aber auch nicht hochgesetzt. Das ist eine eigene Query die nur beim RSS Crawler aufgerufen wird
