### ISSUE TITLE
Responsive HTML-Mail

### ISSUE THREAD

**Issue by ede1998** [InvisibleUSA/METLAB_News#97]
Ich habe herausgefunden, warum in der Mail null steht:

Beim Erstellen der Mail wird die methode createHTMLMail aufgerufen.
Diese gibt m_HTMLMessage zurueck.  Dies ist ein final String. Wenn er erstellt wird ist content noch null.
```java
public String createHTMLMail(String content)
	{
		m_content = content;
		return m_HTMLMessage;
	}
private final String m_HTMLMessage = "blablabla" + m_content + "blablabla";
```

Das kann so nicht funktionieren. Sobald die Instanz von Resp.HTMLMessage erstellt wird, steht fest wie die HTML messsage aussieht. und da ist eben content noch null. 

Eine weitere Anmerkung:  Es macht meiner Meinung nach hier ueberhaupt keinen Sinn eine Singleton Klasse zu verwenden. Die Klasse ist nicht threadsicher, da sie Singleton ist. Dies kann zu Fehlern in den versendeten Clippiungs fuehren.

**Comment by Toberto91** [comment]
https://github.com/InvisibleUSA/METLAB_News/commit/c2e37dcd1acbaed9971a6d847f35c5654c5989df
