### ISSUE TITLE
Installationsskript

### ISSUE THREAD

**Issue by ede1998** [InvisibleUSA/METLAB_News#98]
Kann mal bitte jeder, der eine externe Dependency hat aufschreiben, was und wie es auf dem Server installiert werden muss

Zb tomcat, yacy, mariadb, habe ich was vergessen

**Comment by Toberto91** [comment]
@BentiGorlich kümmert sich um:
- Installationsskript
- Installationsanleitung

**Comment by BentiGorlich** [comment]
also das Installationsskript können wir glaube ich vergessen ^^. Das werden wir nicht schaffen und es wird ihn nicht interessieren... Die Anleitung mache ich dann noch

**Comment by Toberto91** [comment]
Anleitung erledigt

Skript.. fuck off
